---
title: "Scopus Codes"
subtitle: "January 2019 - May 2025)"
author: "Emilio M. Bruna"
date: "`r format(Sys.time(), '%d %B %Y')`"
# output: html_document
output: pdf_document
geometry: margin=1in
fontsize: 11pt
linkcolor: darkmidnightblue
urlcolor: darkmidnightblue
header-includes:
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
  - \usepackage[default]{sourcesanspro}
  - \usepackage{parskip}
  - \usepackage{geometry}
  - \usepackage{caption}
  - \usepackage{xcolor}
  - \definecolor{darkmidnightblue}{rgb}{0.0, 0.2, 0.4}
  - \AtBeginDocument{\let\maketitle\relax}
  - \usepackage[none]{hyphenat}
  - \usepackage{setspace}
  - \usepackage[document]{ragged2e}
  - \usepackage{graphicx}
  - \usepackage{sectsty}\allsectionsfont{\raggedright}
  - \usepackage{sectsty}\sectionfont{\centering\color{darkmidnightblue}}
  - \usepackage{sectsty}\subsectionfont{\centering\color{darkmidnightblue}}
  - \usepackage{titlesec}
  - \usepackage[export]{adjustbox}
  - \titlespacing{\section}{0pt}{24pt plus 2pt minus 1pt}{0pt plus 1pt minus 1pt}
  - \titlespacing{\subsection}{0pt}{12pt plus 2pt minus 1pt}{0pt plus 1pt minus 1pt}
  - \titlespacing{\subsubsection}{0pt}{12pt plus 2pt minus 1pt}{0pt plus 1pt minus 1pt}
  - \usepackage{floatrow}
  - \DeclareFloatSeparators{mysep}{\hskip-94em}
  # - \floatsetup[figure]{capposition=beside,capbesidesep=mysep,capbesideposition={right, center}}
  - \usepackage{float}
  - \usepackage{wrapfig} 
  - \usepackage{pdflscape}
  - \newcommand{\blandscape}{\begin{landscape}}
  - \newcommand{\elandscape}{\end{landscape}}
  # - \usepackage[font=small,labelfont=bf,labelsep=space]{caption}
  # - \captionsetup{figurename=Fig.,tablename=Table}
  # - \usepackage[labelfont=bf]{caption}
  # - \captionsetup{font=footnotesize, textfont=footnotesize}
  - \fancyfoot{} # cues the use of fancy footer
  - \fancyhead[L]{Emilio M Bruna} # month & year on header left 
  - \fancyhead[R]{`r format(Sys.time(), '%d %B %Y')`} # name and page on header right
#Required for specifying captions t
  # - \usepackage{indentfirst}
  # - \setlength\parindent{22pt} # uncomment if you want indented paragraphs


# https://pubs.usgs.gov/search?q=&startYear=2019&__ncforminfo=Rf6y9tBB_4xn4sDOJ7tdSPmxI5Eu33dcCKy8YpAAAQRE-JJvXyAJAosPJMziEEMnxQE_iCi7dgGWVwrbQe9Gpb9a-7115VxO

---

## Supplementary Materials - Scopus Affiliation Codes for Focal Universities

```{r setup, include=FALSE}

library(tidyverse)
library(janitor)
library(gghighlight)
library(kableExtra)
library(data.table)
# library(knitr)

knitr::opts_chunk$set(echo = FALSE, message=FALSE,warning=FALSE)

options(scipen=999)

comma <- function(x) format(x, digits = 2, big.mark = ",")

knitr::opts_chunk$set(fig.pos = 'H')

knitr::opts_chunk$set(dpi=300,fig.width=6)

```




<!-- \begin{document} -->

<!-- \begin{landscape} -->
 

 

```{r journals }


scopus_id<-read_csv("./data_clean/uni_affils_clean.csv") %>% 
  mutate(uni=case_when(
    # uni == "minn"~"other",
    uni == "unc_ch"~"other",
    uni == "ohio_state"~"other",
    is.na(uni) ~ "other",
    .default = as.character(uni)
  )) %>% 
  filter(uni!="other") %>%
  filter(uni!="mass_general") %>%
  # filter(uni=="florida") %>%
  # slice_head(n=30) %>% 
  distinct(affil_id,.keep_all=TRUE) %>% 
  arrange(uni,desc(pub_count)) %>% 
  select(uni,affil_id,affiliation) %>% 
  mutate(uni=case_when(
    uni == "florida"~"University of Florida",
    uni == "harvard"~"Harvard University",
    uni == "mass_general"~"Massachusetts General Hospital",
    uni == "michigan"~"University of Michigan",
    uni == "penn"~"University of Pennsylvania",
    uni == "stanford"~"Stanford University",
    uni == "ucla"~"University of California, Los Angeles",
    uni == "minn"~"University of Minnesota",
    uni == "ucsd"~"University of California, San Diego",
    uni == "ucsf"~"University of California, San Francisco",
    uni == "washington"~"University of Washington",
    .default = as.character(uni)
  )) %>% 
  # select(uni,ids,affils) %>% 
  distinct() %>% 
  select(`Scopus ID`=affil_id,Affiliation=affiliation) 
  
# %>% 
#   mutate(row=row_number())

# scopus_id %>% group_by(uni) %>% tally() %>% mutate(row_start=cumsum(n)-n+1) %>% mutate(row_end=cumsum(n))

scopus_id %>% 
  kable(
      format    = "latex", 
      longtable = T, 
      booktabs  = T, 
      caption   = "Scopus affiliation IDs used in the search of research productivity by ten universities. These affiliations are the affiliations nested under a university's institution code.",
      align = "ll",
      ) %>%
# kable(digits = 2,
#   format = "latex",
#   align = "lll",
#   escape = FALSE,
#   row.names = FALSE,
#   booktabs = T,
#   linesep = ""
# ) %>%
  kable_styling(
    # longtable = T, 
    bootstrap_options = c("hover"),
    full_width = T,
    latex_options = c("hold_position", "repeat_header"),
    repeat_header_continued = "\\textit{(Continued on next page...)}",
    position = "center",
    font_size = 10
  ) %>% 
  row_spec(0, bold = T) %>%
  column_spec(1, width = "10em") %>%
  column_spec(2, width = "37em") %>% 
  # column_spec(3, width = "25em") %>% 
  pack_rows("University of Florida",1,30) %>% 
  pack_rows("Harvard University",31,91) %>% 
  pack_rows("University of Michigan",92,113) %>% 
  pack_rows("University of Minnesota",114,135) %>% 
  pack_rows("University of Pennsylvania",136,169) %>% 
  pack_rows("Stanford University",170,206) %>% 
  pack_rows("University of California, Los Angeles",207,229) %>% 
  pack_rows("University of California, San Diego",230,393) %>% 
  pack_rows("University of California, San Francisco",394,411) %>% 
  pack_rows("University of Washington",412,438)  
  


# scopus_id<-read_csv("./data_clean/uni_affils_clean.csv") %>% 
#   mutate(uni=case_when(
#     uni == "minn"~"other",
#     uni == "unc_ch"~"other",
#     uni == "ohio_state"~"other",
#     is.na(uni) ~ "other",
#     .default = as.character(uni)
#   )) %>% 
#   filter(uni!="other") %>%
#   filter(uni!="mass_general") %>%
#   # filter(uni=="florida") %>%
#   # slice_head(n=30) %>% 
#   distinct(affil_id,.keep_all=TRUE) %>% 
#   arrange(uni,desc(pub_count)) %>% 
#   select(uni,affil_id,affiliation) %>% 
#   group_by(uni) %>% 
#   mutate(ids=paste(affil_id,collapse=", ")) %>% 
#   mutate(affils=paste(affiliation,collapse=", ")) %>% 
#   mutate(uni=case_when(
#     uni == "florida"~"University of Florida",
#     uni == "harvard"~"Harvard University",
#     uni == "mass_general"~"Massachusetts General Hospital",
#     uni == "michigan"~"University of Michigan",
#     uni == "penn"~"University of Pennsylvania",
#         uni == "stanford"~"Stanford University",
#     uni == "ucla"~"University of California, Los Angeles",
#     uni == "minn"~"University of Minnesota",
#     uni == "ucsd"~"University of California, San Diego",
#         uni == "ucsf"~"University of California, San Francisco",
#     uni == "washington"~"University of Washington",
#     .default = as.character(uni)
#   )) %>% 
#   # select(uni,ids,affils) %>% 
#   select(uni,ids,affils) %>% 
#   distinct()
# scopus_id %>% 
#   kable(
#       format    = "latex", 
#       longtable = T, 
#       booktabs  = T, 
#       caption   = "Longtable"
#       ) %>%
# # kable(digits = 2,
# #   format = "latex",
# #   align = "lll",
# #   escape = FALSE,
# #   row.names = FALSE,
# #   booktabs = T,
# #   linesep = ""
# # ) %>%
#   kable_styling(
#     # longtable = T, 
#     bootstrap_options = c("hover"),
#     full_width = T,
#     latex_options = c("hold_position", "repeat_header"),
#     repeat_header_continued = "\\textit{(Continued on Next Page...)}",
#     position = "center",
#     font_size = 12
#   ) %>% 
#   row_spec(0, bold = T) %>%
#   column_spec(1, width = "5em") %>%
#   column_spec(2, width = "10em") %>% 
#   column_spec(3, width = "25em") 
```

<!-- \end{landscape} -->
